WIT_API_TOKEN = "xxxx"


ASSEMBLYAI_API_KEY = "xxx"

# ✅ SETTINGS
AUDIO_DOWNLOAD_TIMEOUT = 30  # detik
TRANSCRIPTION_TIMEOUT = 60   # detik
TEMP_AUDIO_DIR = "temp_audio"

# ✅ FALLBACK SETTINGS
USE_WIT_AI_FIRST = True      
CLEANUP_TEMP_FILES = True    